### ISSUE TITLE
community process?

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible/galaxy-lint-rules#1]
Is this ruleset community driven? Once the three well-know  rulesets are in place I’d appreciate an open discussion of the best practices to be implemented in (strict) rules, and the lienience on others.

**Comment by robertdebock** [comment]
@bbaassssiiee, I see many pull-request-discussion coming, but; I'd appreciate input for everybody as well.

**Comment by awcrosby** [comment]
We do want community input on the rules. Likely this will be a temporary repo, and we'll move to using the default ansible-lint rules... with any additions or edits going through community PR discussions.
