### ISSUE TITLE
LineTooLongRule - how to deal with it?

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy-lint-rules#4]
I have a number of cases where an entire repo has lines under 80 chars or 120 chars (the most common line length limits I live by), but every now and then there's a line (e.g. in a vars file) that requires a large number more characters, lest the variable end up being really hard to work with. For example, this var in the defaults/main.yml file from my `geerlingguy.docker` role:

```yaml
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
```

(193 characters)

Is there any better option of fixing a lint issue like this, or should those of us who try to make flexible variables just suffer the loss of perceived code quality due to the use of variables here? :-/

**Comment by geerlingguy** [comment]
Note that the easiest fix is to break the thing to multiple lines, but when you do, if you just use the folded scalar `>` then it adds a newline character to the end:

```yaml
docker_apt_repository: >
  deb [arch={{ docker_apt_arch }}]
  https://download.docker.com/linux/{{ ansible_distribution|lower }}
  {{ ansible_distribution_release }}
  {{ docker_apt_release_channel }}
```

So instead, you have to use an even weirder construct:

```yaml
docker_apt_repository: >-
  deb [arch={{ docker_apt_arch }}]
  https://download.docker.com/linux/{{ ansible_distribution|lower }}
  {{ ansible_distribution_release }}
  {{ docker_apt_release_channel }}
```

**Comment by awcrosby** [comment]
I see from previous conversations ansible/ansible uses 160 for pylint and pep8, and we want to match that, so we will change this from 100 to 160. Also ansible-lint supports [excluding certain tasks from being linted](https://github.com/willthames/ansible-lint#false-positives), that might not be the best approach but is an option for the 193 character task.

**Comment by geerlingguy** [comment]
@awcrosby good to know, as 160 is a better gate in general (though I usually use 120, I know a lot of people have gone wider in recent years).

The task exclusion works great, but the rules also apply to vars files like role defaults, and you sadly can't tag a variable—it would be interesting if you were able to exclude a particular line (e.g. a variable line) using a comment like `# skip-ansible-lint` or something. I know you can do this with other linters I use, e.g. phpcs has [`// phpcs:disable`](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file)

**Comment by geerlingguy** [comment]
See upstream closed issue: https://github.com/willthames/ansible-lint/issues/132

**Comment by geerlingguy** [comment]
All right, looks like this is taken care of by the commit above, plus the fact that ansible lint _currently_ doesn't lint vars files—see https://github.com/willthames/ansible-lint/issues/354 for progress on that issue.
